# Site settings
title: OpenSauce
email: hello@opensauce.io
url: https://opensauce.io
description: "We're Contributing to the Open Source World."
description_more: "We're a Web/Mobile App Design & Development Team - -"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: opensauce.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: wechat
    url:
  - title: github
    url: https://github.com/opensauce-io

# Build settings
markdown: kramdown
permalink: pretty
